const teamUSA = [
  {
    forwards: [
      { playerName: "Trevor Zegras", number: 9, shots: 0 },
      { playerName: "Alex Turcotte", number: 15, shots: 0 },
      { playerName: "Landon Slaggert", number: 26, shots: 0 },
      { playerName: "Patrick Moynihan", number: 19, shots: 0 },
      { playerName: "Arthur Kaliyev", number: 28, shots: 0 },
      { playerName: "John Farinacci", number: 25, shots: 0 },
      { playerName: "Sam Colangelo", number: 22, shots: 0 },
      { playerName: "Cole Caufield", number: 13, shots: 0 },
      { playerName: "Brendan Brisson", number: 18, shots: 0 },
      { playerName: "Bobby Brink", number: 24, shots: 0 },
      { playerName: "Matthew Boldy", number: 12, shots: 0 },
      { playerName: "Brett Berard", number: 21, shots: 0 },
      { playerName: "Matthew Beniers", number: 10, shots: 0 },
      // {playerName: '',
      // number: ,
      // shots: 0},
    ],
    defensemen: [
      { playerName: "Cam York", number: 4, shots: 0 },
      { playerName: "Henry Thrun", number: 3, shots: 0 },
      { playerName: "Hunter Skinner", number: 17, shots: 0 },
      { playerName: "Jake Sanderson", number: 8, shots: 0 },
      { playerName: "Jackson LaCombe", number: 5, shots: 0 },
      { playerName: "Tyler Kleven", number: 7, shots: 0 },
      { playerName: "Ryan Johnson", number: 23, shots: 0 },
      { playerName: "Drew Helleson", number: 2, shots: 0 },
      { playerName: "Brock Faber", number: 11, shots: 0 },
    ],
  },
];

const teamCAN = [
  {
    forwards: [
      { playerName: "Jack Quinn", number: 29, shots: 0 },
      { playerName: "Philip Tomasino", number: 26, shots: 0 },
      { playerName: "Dylan Cozens", number: 22, shots: 0 },
      { playerName: "Dawson Mercer", number: 20, shots: 0 },
      { playerName: "Quinton Byfield", number: 19, shots: 0 },
      { playerName: "Peyton Krebs", number: 18, shots: 0 },
      { playerName: "Connor McMichael", number: 17, shots: 0 },
      { playerName: "Ryan Suzuki", number: 16, shots: 0 },
      { playerName: "Alex Newhook", number: 15, shots: 0 },
      { playerName: "Jakob Pelletier", number: 12, shots: 0 },
      { playerName: "Cole Perfetti", number: 11, shots: 0 },
      { playerName: "Dylan Holloway", number: 10, shots: 0 },
      { playerName: "Connor Zary", number: 9, shots: 0 },
      { playerName: "Kirby Dach", number: 7, shots: 0 },
    ],
    defensemen: [
      { playerName: "Braden Schneider", number: 2, shots: 0 },
      { playerName: "Kaedan Korczak", number: 3, shots: 0 },
      { playerName: "Bowen Byram", number: 4, shots: 0 },
      { playerName: "Thomas Harley", number: 5, shots: 0 },
      { playerName: "Jamie Drysdale", number: 6, shots: 0 },
      { playerName: "Jordan Spence", number: 8, shots: 0 },
      { playerName: "Kaiden Guhle", number: 21, shots: 0 },
      { playerName: "Justin Barrow", number: 27, shots: 0 },
      // {playerName: '',
      // number: ,
      // shots: 0},
    ],
  },
];
// const teamSWE = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]
const teamRUS = [
  {
    forwards: [
      { playerName: "Arseny Gritsyuk", number: 8, shots: 0 },
      { playerName: "Mikhail Abramov", number: 9, shots: 0 },
      { playerName: "Vladislav Firstov", number: 10, shots: 0 },
      { playerName: "Zakhar Bardakov", number: 11, shots: 0 },
      { playerName: "Vasiliy Ponomarev", number: 13, shots: 0 },
      { playerName: "Yegor Spiridonov", number: 18, shots: 0 },
      { playerName: "Vasily Podkolzin", number: 19, shots: 0 },
      { playerName: "Yegor Chinakhov", number: 21, shots: 0 },
      { playerName: "Marat Khusnutdinov", number: 22, shots: 0 },
      { playerName: "Yegor Afanasyev", number: 23, shots: 0 },
      { playerName: "Ilya Safonov", number: 24, shots: 0 },
      { playerName: "Danil Bashkirov", number: 25, shots: 0 },
      { playerName: "Rodion Amirov", number: 27, shots: 0 },
      { playerName: "Maxim Groshev", number: 28, shots: 0 },
    ],
    defensemen: [
      { playerName: "Yan Kuznetsov", number: 2, shots: 0 },
      { playerName: "	Artemi Kniazev", number: 3, shots: 0 },
      { playerName: "Daniil Chayka", number: 5, shots: 0 },
      { playerName: "Semyon Chistyakov", number: 6, shots: 0 },
      { playerName: "Roman Bychkov", number: 7, shots: 0 },
      { playerName: "Yegor Shekhovtsov", number: 14, shots: 0 },
      { playerName: "Shakir Mukhamadullin", number: 17, shots: 0 },
      { playerName: "Kirill Kirsanov", number: 20, shots: 0 },
    ],
  },
];

// const teamSUI = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]

// const teamFIN = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]

// const teamSVK = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]

// const teamKAZ = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]
// const teamCZE = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]
// const teamGER = [{
//     forwards : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ],
//     defensemen : [
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//         {playerName: '',
//         number: ,
//         shots: 0},
//     ]
// }
// ]
export { teamUSA, teamCAN, teamRUS };
