const teamUSA = [
  {
    forwards: [
      { playerName: "Trevor Zegras", number: 9, shots: 0 },
      { playerName: "Alex Turcotte", number: 15, shots: 0 },
      { playerName: "Landon Slaggert", number: 26, shots: 0 },
      { playerName: "Patrick Moynihan", number: 19, shots: 0 },
      { playerName: "Arthur Kaliyev", number: 28, shots: 0 },
      { playerName: "John Farinacci", number: 25, shots: 0 },
      { playerName: "Sam Colangelo", number: 22, shots: 0 },
      { playerName: "Cole Caufield", number: 13, shots: 0 },
      { playerName: "Brendan Brisson", number: 18, shots: 0 },
      { playerName: "Bobby Brink", number: 24, shots: 0 },
      { playerName: "Matthew Boldy", number: 12, shots: 0 },
      { playerName: "Brett Berard", number: 21, shots: 0 },
      { playerName: "Matthew Beniers", number: 10, shots: 0 },
      // {playerName: '',
      // number: ,
      // shots: 0},
    ],
    defensemen: [
      { playerName: "Cam York", number: 4, shots: 0 },
      { playerName: "Henry Thrun", number: 3, shots: 0 },
      { playerName: "Hunter Skinner", number: 17, shots: 0 },
      { playerName: "Jake Sanderson", number: 8, shots: 0 },
      { playerName: "Jackson LaCombe", number: 5, shots: 0 },
      { playerName: "Tyler Kleven", number: 7, shots: 0 },
      { playerName: "Ryan Johnson", number: 23, shots: 0 },
      { playerName: "Drew Helleson", number: 2, shots: 0 },
      { playerName: "Brock Faber", number: 11, shots: 0 },
    ],
  },
];

const teamCAN = [
  {
    forwards: [
      { playerName: "Jack Quinn", number: 29, shots: 0 },
      { playerName: "Philip Tomasino", number: 26, shots: 0 },
      { playerName: "Dylan Cozens", number: 22, shots: 0 },
      { playerName: "Dawson Mercer", number: 20, shots: 0 },
      { playerName: "Quinton Byfield", number: 19, shots: 0 },
      { playerName: "Peyton Krebs", number: 18, shots: 0 },
      { playerName: "Connor McMichael", number: 17, shots: 0 },
      { playerName: "Ryan Suzuki", number: 16, shots: 0 },
      { playerName: "Alex Newhook", number: 15, shots: 0 },
      { playerName: "Jakob Pelletier", number: 12, shots: 0 },
      { playerName: "Cole Perfetti", number: 11, shots: 0 },
      { playerName: "Dylan Holloway", number: 10, shots: 0 },
      { playerName: "Connor Zary", number: 9, shots: 0 },
      { playerName: "Kirby Dach", number: 7, shots: 0 },
    ],
    defensemen: [
      { playerName: "Braden Schneider", number: 2, shots: 0 },
      { playerName: "Kaedan Korczak", number: 3, shots: 0 },
      { playerName: "Bowen Byram", number: 4, shots: 0 },
      { playerName: "Thomas Harley", number: 5, shots: 0 },
      { playerName: "Jamie Drysdale", number: 6, shots: 0 },
      { playerName: "Jordan Spence", number: 8, shots: 0 },
      { playerName: "Kaiden Guhle", number: 21, shots: 0 },
      { playerName: "Justin Barrow", number: 27, shots: 0 },
      // {playerName: '',
      // number: ,
      // shots: 0},
    ],
  },
];
const teamSWE = [
  {
    forwards: [
      { playerName: "Alexander Holtz", number: 10, shots: 0 },
      { playerName: "Emil Heineman", number: 13, shots: 0 },
      { playerName: "Arvid Costmar", number: 14, shots: 0 },
      { playerName: "Simon Holmstrom", number: 15, shots: 0 },
      { playerName: "Theodor Niederbach", number: 16, shots: 0 },
      { playerName: "Oskar Kvist", number: 17, shots: 0 },
      { playerName: "Lucas Raymond", number: 18, shots: 0 },
      { playerName: "Oscar Bjerselius", number: 21, shots: 0 },
      { playerName: "Oskar Olausson", number: 24, shots: 0 },
      { playerName: "Elmer Soderblom", number: 25, shots: 0 },
      { playerName: "Zion Nybeck", number: 27, shots: 0 },
      { playerName: "Noel Gunler", number: 28, shots: 0 },
      { playerName: "Albin Sundsvik", number: 29, shots: 0 },
      { playerName: "Jonathan Wikstrom", number: 23, shots: 0 },
    ],
    defensemen: [
      { playerName: "Tobias Bjornfot", number: 3, shots: 0 },
      { playerName: "Emil Andrae", number: 4, shots: 0 },
      { playerName: "Philip Broberg", number: 5, shots: 0 },
      { playerName: "Ludvig Hedstrom", number: 6, shots: 0 },
      { playerName: "Gustav Berglund", number: 7, shots: 0 },
      { playerName: "Victor Soderstrom", number: 8, shots: 0 },
      { playerName: "Albert Johansson", number: 9, shots: 0 },
      { playerName: "Alex Brannstam", number: 26, shots: 0 },
    ],
  },
];
const teamRUS = [
  {
    forwards: [
      { playerName: "Arseny Gritsyuk", number: 8, shots: 0 },
      { playerName: "Mikhail Abramov", number: 9, shots: 0 },
      { playerName: "Vladislav Firstov", number: 10, shots: 0 },
      { playerName: "Zakhar Bardakov", number: 11, shots: 0 },
      { playerName: "Vasiliy Ponomarev", number: 13, shots: 0 },
      { playerName: "Yegor Spiridonov", number: 18, shots: 0 },
      { playerName: "Vasily Podkolzin", number: 19, shots: 0 },
      { playerName: "Yegor Chinakhov", number: 21, shots: 0 },
      { playerName: "Marat Khusnutdinov", number: 22, shots: 0 },
      { playerName: "Yegor Afanasyev", number: 23, shots: 0 },
      { playerName: "Ilya Safonov", number: 24, shots: 0 },
      { playerName: "Danil Bashkirov", number: 25, shots: 0 },
      { playerName: "Rodion Amirov", number: 27, shots: 0 },
      { playerName: "Maxim Groshev", number: 28, shots: 0 },
    ],
    defensemen: [
      { playerName: "Yan Kuznetsov", number: 2, shots: 0 },
      { playerName: "	Artemi Kniazev", number: 3, shots: 0 },
      { playerName: "Daniil Chayka", number: 5, shots: 0 },
      { playerName: "Semyon Chistyakov", number: 6, shots: 0 },
      { playerName: "Roman Bychkov", number: 7, shots: 0 },
      { playerName: "Yegor Shekhovtsov", number: 14, shots: 0 },
      { playerName: "Shakir Mukhamadullin", number: 17, shots: 0 },
      { playerName: "Kirill Kirsanov", number: 20, shots: 0 },
    ],
  },
];

const teamSUI = [
  {
    forwards: [
      { playerName: "Mika Burkhalter", number: 7, shots: 0 },
      { playerName: "Simon Knak", number: 8, shots: 0 },
      { playerName: "Attilio Biasca", number: 9, shots: 0 },
      { playerName: "Elvis Schlapfer", number: 10, shots: 0 },
      { playerName: "Lionel Marchand", number: 11, shots: 0 },
      { playerName: "Dario Allenspach", number: 12, shots: 0 },
      { playerName: "Valentin Hofer", number: 13, shots: 0 },
      { playerName: "Lorenzo Canonica", number: 14, shots: 0 },
      { playerName: "Ronny Dahler", number: 15, shots: 0 },
      { playerName: "Jeremie Bartschi", number: 16, shots: 0 },
      { playerName: "Keanu Derungs", number: 19, shots: 0 },
      { playerName: "Stefano Bottini", number: 20, shots: 0 },
      { playerName: "Joel Salzgeber", number: 22, shots: 0 },
      { playerName: "Gaetan Jobin", number: 27, shots: 0 },
      { playerName: "Raymond Fust", number: 28, shots: 0 },
    ],
    defensemen: [
      { playerName: "Bastian Guggenheim", number: 2, shots: 0 },
      { playerName: "Noah Delemont", number: 4, shots: 0 },
      { playerName: "Giancarlo Chanton", number: 5, shots: 0 },
      { playerName: "Brian Zanetti", number: 6, shots: 0 },
      { playerName: "Alessandro Villa", number: 17, shots: 0 },
      { playerName: "Inaki Baragano", number: 18, shots: 0 },
      { playerName: "Nathan Vouardoux", number: 21, shots: 0 },
      { playerName: "Cedric Fiedler", number: 23, shots: 0 },
      { playerName: "Noah Meier", number: 24, shots: 0 },
      { playerName: "Rocco Pezzullo", number: 26, shots: 0 },
    ],
  },
];

const teamFIN = [
  {
    forwards: [
      { playerName: "Roby Jarventie", number: 13, shots: 0 },
      { playerName: "Anton Lundell", number: 15, shots: 0 },
      { playerName: "Petteri Puhakka", number: 19, shots: 0 },
      { playerName: "Samuel Helenius", number: 20, shots: 0 },
      { playerName: "Mikael Pyyhtia", number: 21, shots: 0 },
      { playerName: "Roni Hirvonen", number: 22, shots: 0 },
      { playerName: "Mikko Petman", number: 23, shots: 0 },
      { playerName: "Juuso Parssinen", number: 27, shots: 0 },
      { playerName: "Henri Nikkanen", number: 28, shots: 0 },
      { playerName: "Kasper Simontaival", number: 29, shots: 0 },
      { playerName: "Matias Mantykivi", number: 32, shots: 0 },
      { playerName: "Brad Lambert", number: 33, shots: 0 },
      { playerName: "Aku Raty", number: 34, shots: 0 },
      { playerName: "Benhamin Korhonen", number: 36, shots: 0 },
    ],
    defensemen: [
      { playerName: "Santeri Hatakka", number: 2, shots: 0 },
      { playerName: "Ruben Rafkin", number: 3, shots: 0 },
      { playerName: "Ville Heinola", number: 4, shots: 0 },
      { playerName: "Eemil Viro", number: 6, shots: 0 },
      { playerName: "Topi Niemela", number: 7, shots: 0 },
      { playerName: "Kasper Puutio", number: 10, shots: 0 },
      { playerName: "Matias Rajaniemi", number: 12, shots: 0 },
      { playerName: "Mikko Kokkonen", number: 35, shots: 0 },
    ],
  },
];

const teamSVK = [
  {
    forwards: [
      { playerName: "Robert Baco", number: 998, shots: 0 },
      { playerName: "Martin Chromiak", number: 8, shots: 0 },
      { playerName: "Michael Drabek", number: 997, shots: 0 },
      { playerName: "Juraj Elias", number: 27, shots: 0 },
      { playerName: "Roman Faith", number: 9, shots: 0 },
      { playerName: "Maros Jedlicka", number: 22, shots: 0 },
      { playerName: "Simon Jellus", number: 19, shots: 0 },
      { playerName: "Dominik Jendek", number: 14, shots: 0 },
      { playerName: "Matej Kaslik", number: 11, shots: 0 },
      { playerName: "Jakub Kolenic", number: 13, shots: 0 },
      { playerName: "Filip Mesar", number: 15, shots: 0 },
      { playerName: "Michal Mrazik", number: 25, shots: 0 },
      { playerName: "Oleksiy Myklukha", number: 10, shots: 0 },
      { playerName: "Juraj Slafkovsky", number: 18, shots: 0 },
      { playerName: "Dominik Sojka", number: 7, shots: 0 },
      { playerName: "Artur Turansky", number: 17, shots: 0 },
    ],
    defensemen: [
      { playerName: "Simon Becar", number: 3, shots: 0 },
      { playerName: "Andrej Golian", number: 24, shots: 0 },
      { playerName: "Simon Groch", number: 999, shots: 0 },
      { playerName: "Matus Hlavac", number: 996, shots: 0 },
      { playerName: "Samuel Knazko", number: 20, shots: 0 },
      { playerName: "David Mudrak", number: 4, shots: 0 },
      { playerName: "Simon Nemec", number: 5, shots: 0 },
      { playerName: "Rayen Petrovicky", number: 12, shots: 0 },
      { playerName: "Marko Stacha", number: 16, shots: 0 },
      { playerName: "Oliver Turan", number: 23, shots: 0 },
    ],
  },
];

const teamAUT = [
  {
    forwards: [
      { playerName: "Maximilian Theirirch", number: 3, shots: 0 },
      { playerName: "Clemens Krainz", number: 6, shots: 0 },
      { playerName: "Marlon Tschofen", number: 7, shots: 0 },
      { playerName: "Mathias Bohm", number: 9, shots: 0 },
      { playerName: "Maximillian Hengelmuller", number: 11, shots: 0 },
      { playerName: "Leon Wallner", number: 13, shots: 0 },
      { playerName: "Dominik Unterweger", number: 16, shots: 0 },
      { playerName: "Marco Kasper", number: 19, shots: 0 },
      { playerName: "Fabian Hochegger", number: 20, shots: 0 },
      { playerName: "Tim Harnisch", number: 21, shots: 0 },
      { playerName: "Senna Peeters", number: 22, shots: 0 },
      { playerName: "Marco Rossi", number: 23, shots: 0 },
      { playerName: "Lucas Thaler", number: 24, shots: 0 },
      { playerName: "Finn van Ee", number: 26, shots: 0 },
      { playerName: "Julian Pauschenwein", number: 27, shots: 0 },
    ],
    defensemen: [
      { playerName: "Bernhard Posch", number: 2, shots: 0 },
      { playerName: "Philipp Wimmer", number: 4, shots: 0 },
      { playerName: "Jacob Pfeffer", number: 5, shots: 0 },
      { playerName: "Timo Pallierer", number: 12, shots: 0 },
      { playerName: "Jonas Kutzer", number: 14, shots: 0 },
      { playerName: "Luis Lindner", number: 15, shots: 0 },
      { playerName: "Niklas Wetzl", number: 17, shots: 0 },
      { playerName: "Lukas Necesany", number: 25, shots: 0 },
      { playerName: "Moritz Molls", number: 28, shots: 0 },
    ],
  },
];
const teamCZE = [
  {
    forwards: [
      { playerName: "Radek Muzik", number: 29, shots: 0 },
      { playerName: "Filip Koffer", number: 27, shots: 0 },
      { playerName: "Adam Raska", number: 26, shots: 0 },
      { playerName: "Jakub Rychlovsky", number: 25, shots: 0 },
      { playerName: "Martin Beranek", number: 24, shots: 0 },
      { playerName: "Jaromir Pytlik", number: 21, shots: 0 },
      { playerName: "Jan Mysak", number: 19, shots: 0 },
      { playerName: "David Vitouch", number: 18, shots: 0 },
      { playerName: "Michal Gut", number: 17, shots: 0 },
      { playerName: "Adam Najman", number: 16, shots: 0 },
      { playerName: "Filip Prikryl", number: 15, shots: 0 },
      { playerName: "Pavel Novak", number: 13, shots: 0 },
      { playerName: "Michal Teply", number: 11, shots: 0 },
      { playerName: "Martin Lang", number: 10, shots: 0 },
    ],
    defensemen: [
      { playerName: "Karel Klikorka", number: 3, shots: 0 },
      { playerName: "Radek Kucerik", number: 4, shots: 0 },
      { playerName: "Stanislav Svozil", number: 5, shots: 0 },
      { playerName: "Martin Has", number: 7, shots: 0 },
      { playerName: "David Jiricek", number: 8, shots: 0 },
      { playerName: "Jiri Suhrada", number: 22, shots: 0 },
      { playerName: "Simon Kubicek", number: 23, shots: 0 },
      { playerName: "Michael Krutil", number: 28, shots: 0 },
    ],
  },
];
const teamGER = [
  {
    forwards: [
      { playerName: "Florian Elias", number: 7, shots: 0 },
      { playerName: "Tim Stutzle", number: 8, shots: 0 },
      { playerName: "Joshua Samanski", number: 9, shots: 0 },
      { playerName: "Filip Reisnecker", number: 10, shots: 0 },
      { playerName: "Jan Nijenhuis", number: 11, shots: 0 },
      { playerName: "Markus Schweiger", number: 13, shots: 0 },
      { playerName: "Julian Chrobot", number: 14, shots: 0 },
      { playerName: "Justin Volek", number: 15, shots: 0 },
      { playerName: "Jan-Luca Schumacher", number: 18, shots: 0 },
      { playerName: "Samuel Dube", number: 19, shots: 0 },
      { playerName: "Jakub Borzecki", number: 20, shots: 0 },
      { playerName: "John-Jason Peterka", number: 24, shots: 0 },
      { playerName: "Enrico Henriquez-Morales", number: 26, shots: 0 },
      { playerName: "Manuel Alberg", number: 28, shots: 0 },
    ],
    defensemen: [
      { playerName: "	Simon Gnyp", number: 3, shots: 0 },
      { playerName: "Maksymilian Szuber", number: 4, shots: 0 },
      { playerName: "Lucas Flade", number: 5, shots: 0 },
      { playerName: "Niklas Langer", number: 6, shots: 0 },
      { playerName: "Steven Raabe", number: 17, shots: 0 },
      { playerName: "Maximillian Glotzl", number: 22, shots: 0 },
      { playerName: "Mario Zimmermann", number: 25, shots: 0 },
      { playerName: "Luca Munzenberger", number: 27, shots: 0 },
    ],
  },
];
export {
  teamUSA,
  teamCAN,
  teamRUS,
  teamSUI,
  teamSVK,
  teamGER,
  teamFIN,
  teamAUT,
  teamSWE,
  teamCZE,
};
